### PR TITLE
Add netstandard2.0 to TargetFrameworks

### PR DESCRIPTION
**Pull request by mbrookson**
Add proper support for netstandard2.0 projects. Should be a simple addition since the dependencies used all already support netstandard2.0

### CODE REVIEW

**Comment by davidbilling** [comment]
@amitsendinblue When will this be merged and released in a nuget? When using Azure everything is setup for SendGrid. But it is kind of crap. If you release this and later do a binder for functions, you will win alot of customer there... =)

**Comment by mbrookson** [comment]
Hi @amitsendinblue, is there any update on when .netstandard will be officially supported? I have deployed a project using the existing package to a Linux environment and run locally on a Mac and it seems to work as expected.

Would be great to see this project maintained properly. Thanks!

**Comment by amitsendinblue** [comment]
Hi @mbrookson, we need to update this wrapper, requested change will be taken care with that update itself.
Thanks

**Comment by mbrookson** [comment]
Thanks @amitsendinblue, that's great! Any idea when this might be done?

**Comment by amitsendinblue** [comment]
@mbrookson It will be done in next quarter.

**Comment by sergio1359** [comment]
Hi @amitsendinblue we need the official netcore/netstandard2.0 release. Do you think it would be possible to have this next month? Thanks.

**Comment by amitsendinblue** [comment]
Hi @mbrookson , @davidbilling , @sergio1359 I have incorporated suggested changes to the following branch, could you please check at you end if these changes are working fine for you. In either case please let me know.

https://github.com/sendinblue/APIv3-csharp-library/tree/UpdateWrapper

Thank you

**Comment by amitsendinblue** [comment]
Hi @mbrookson, we have updated the solution and requested change is incorporated in the same solution, so closing this PR.
Thanks,
Amit Joshi

**Comment by mbrookson** [comment]
@amitsendinblue  Thanks! Haven't had time to test it out yet but do soon 🙂

**Comment by mbrookson** [comment]
FYI anyone who lands here, this was fixed in https://github.com/sendinblue/APIv3-csharp-library/pull/7

**Pull request closed without merging**
